// SPDX-License-Identifier: MIT
#include "Volleyball/MatchOfficialManager.h"
#include "Components/BoxComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Components/TextRenderComponent.h"
#include "Engine/StaticMesh.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Sound/SoundWaveProcedural.h"
#include "Kismet/GameplayStatics.h"
#include "SEMaterials.h"

static UMaterialInstanceDynamic* MOMakeMID(UObject* Owner, const FLinearColor& Color)
{
	return SEMaterials::MakeTint(Owner, Color);
}

/**
 * Program-generated referee whistle (single 2.2 kHz tone, ~0.35 s, soft
 * fade), streamed through a procedural USoundWave. Created at runtime so there
 * is no external audio asset, no download and no licensing question. License
 * record: generated by this project.
 */
static USoundWaveProcedural* MakeWhistleSound(UObject* Outer)
{
	const int32 SampleRate = 22050;
	const float Dur = 0.35f;
	const int32 Num = (int32)(Dur * SampleRate);
	TArray<uint8> Bytes;
	Bytes.Reserve(Num * 2);
	for (int32 i = 0; i < Num; ++i)
	{
		const float t = (float)i / (float)SampleRate;
		const float Env = FMath::Sin(PI * (float)i / (float)Num);
		const float V = FMath::Sin(2.f * PI * 2200.f * t) * 0.5f * Env;
		const int16 S = (int16)(FMath::Clamp(V, -1.f, 1.f) * 32767.f);
		Bytes.Add((uint8)(S & 0xFF));
		Bytes.Add((uint8)((S >> 8) & 0xFF));
	}
	USoundWaveProcedural* W = NewObject<USoundWaveProcedural>(Outer);
	W->SetSampleRate(SampleRate);
	W->NumChannels = 1;
	W->SampleByteSize = 2;
	W->QueueAudio(Bytes.GetData(), Bytes.Num());
	return W;
}

UStaticMeshComponent* AMatchOfficialManager::MakeBlock(const TCHAR* Name, const FVector& Loc, const FVector& Scale,
	const FLinearColor& Color, ECollisionEnabled::Type Collision)
{
	UStaticMeshComponent* C = CreateDefaultSubobject<UStaticMeshComponent>(Name);
	C->SetupAttachment(Root);
	if (UStaticMesh* Cube = LoadObject<UStaticMesh>(nullptr, TEXT("/Engine/BasicShapes/Cube.Cube")))
		C->SetStaticMesh(Cube);
	C->SetRelativeLocation(Loc);
	C->SetRelativeScale3D(Scale);
	C->SetCollisionEnabled(Collision);
	if (auto* M = MOMakeMID(C, Color)) C->SetMaterial(0, M);
	return C;
}

AMatchOfficialManager::AMatchOfficialManager()
{
	PrimaryActorTick.bCanEverTick = false;

	Root = CreateDefaultSubobject<UBoxComponent>(TEXT("Root"));
	Root->SetBoxExtent(FVector(100.f, 100.f, 10.f));
	Root->SetCollisionProfileName(TEXT("BlockAll"));
	RootComponent = Root;

	BuildStand();
	BuildScorer();
	BuildBenches();
}

void AMatchOfficialManager::BuildStand()
{
	// 1st referee stand at the +Y net end. Platform top ~245 cm so the
	// referee's eye line sits ~50 cm above the net top (243).
	const FVector StandLoc(0.f, 720.f, 0.f);

	StandPlatform = MakeBlock(TEXT("StandPlatform"), StandLoc + FVector(0, 0, 240.f),
		FVector(1.6f, 1.6f, 0.12f), FLinearColor(0.35f, 0.36f, 0.40f), ECollisionEnabled::QueryOnly);
	StandLadder = MakeBlock(TEXT("StandLadder"), StandLoc + FVector(120.f, 0, 110.f),
		FVector(0.9f, 0.9f, 2.2f), FLinearColor(0.30f, 0.31f, 0.35f));
	// Guard rails: two upright posts plus the cross bar so the platform reads
	// as a real referee tower rather than a floating slab.
	StandRailing = MakeBlock(TEXT("StandRailing"), StandLoc + FVector(0, 0, 300.f),
		FVector(1.6f, 0.10f, 0.5f), FLinearColor(0.45f, 0.47f, 0.52f));
	StandRailingPostA = MakeBlock(TEXT("StandRailingPostA"), StandLoc + FVector(-80.f, 0, 280.f),
		FVector(0.12f, 0.12f, 1.6f), FLinearColor(0.45f, 0.47f, 0.52f));
	StandRailingPostB = MakeBlock(TEXT("StandRailingPostB"), StandLoc + FVector(80.f, 0, 280.f),
		FVector(0.12f, 0.12f, 1.6f), FLinearColor(0.45f, 0.47f, 0.52f));
	StandPadding = MakeBlock(TEXT("StandPadding"), StandLoc + FVector(0, 0, 220.f),
		FVector(1.7f, 0.3f, 0.5f), FLinearColor(0.60f, 0.30f, 0.25f));

	// 1st referee (standing on the platform, facing the court = -X).
	Ref1Body = MakeBlock(TEXT("Ref1Body"), StandLoc + FVector(0, 0, 300.f),
		FVector(0.42f, 0.30f, 0.95f), FLinearColor(0.92f, 0.88f, 0.84f));
	Ref1Head = MakeBlock(TEXT("Ref1Head"), StandLoc + FVector(0, 0, 368.f),
		FVector(0.30f, 0.30f, 0.30f), FLinearColor(0.72f, 0.55f, 0.42f));

	// 2nd referee at the -Y net end, on the ground.
	Ref2Body = MakeBlock(TEXT("Ref2Body"), FVector(0.f, -720.f, 55.f),
		FVector(0.42f, 0.30f, 0.95f), FLinearColor(0.90f, 0.55f, 0.15f));
	Ref2Head = MakeBlock(TEXT("Ref2Head"), FVector(0.f, -720.f, 123.f),
		FVector(0.30f, 0.30f, 0.30f), FLinearColor(0.72f, 0.55f, 0.42f));
}

void AMatchOfficialManager::BuildScorer()
{
	// M11f-4: scorer table, scoreboard and BOTH benches form one competition
	// work area on the -Y sideline (outside the free zone, Y < -950), with the
	// scorer table centred and the benches split by team; the 1st referee stays
	// on the opposite (+Y) net end. No furniture sits inside the free zone or
	// mixed into the stands.
	const FVector TableLoc(0.f, -1200.f, 0.f);
	ScorerTable = MakeBlock(TEXT("ScorerTable"), TableLoc + FVector(0, 0, 75.f),
		FVector(1.8f, 2.4f, 0.10f), FLinearColor(0.45f, 0.40f, 0.32f), ECollisionEnabled::QueryOnly);
	ScorerChair = MakeBlock(TEXT("ScorerChair"), TableLoc + FVector(130.f, 0, 30.f),
		FVector(0.5f, 0.5f, 0.6f), FLinearColor(0.35f, 0.36f, 0.40f));
	// Scorer sits behind the table facing the court / 1st referee (+X direction
	// from the -Y aisle, i.e. towards the net). Body below the scoreboard device.
	ScorerBody = MakeBlock(TEXT("ScorerBody"), TableLoc + FVector(70.f, 0, 105.f),
		FVector(0.40f, 0.30f, 0.90f), FLinearColor(0.25f, 0.30f, 0.45f));
	ScorerHead = MakeBlock(TEXT("ScorerHead"), TableLoc + FVector(70.f, 0, 168.f),
		FVector(0.28f, 0.28f, 0.28f), FLinearColor(0.72f, 0.55f, 0.42f));

	// Physical scoreboard device on the table: a wide pedestal plus a tall panel
	// whose FRONT FACE is -X (towards the court, the stands and the broadcast
	// camera). The panel is thin along X (0.06), wide along Y (2.2 m) and the
	// text sits just outside that -X face so glyphs are readable front-on and
	// from a 45-degree angle with no mirrored or board-external text.
	ScoreboardDevice = MakeBlock(TEXT("ScoreboardDevice"), TableLoc + FVector(0, 0, 108.f),
		FVector(0.9f, 2.4f, 0.12f), FLinearColor(0.18f, 0.19f, 0.24f), ECollisionEnabled::QueryOnly);
	ScoreboardPanel = MakeBlock(TEXT("ScoreboardPanel"), TableLoc + FVector(0, 0, 155.f),
		FVector(0.06f, 2.2f, 0.85f), FLinearColor(0.05f, 0.06f, 0.11f), ECollisionEnabled::QueryOnly);

	// Live text: same -X face normal as the panel, offset 5 cm in front to avoid
	// z-fighting; centred horizontally, 4 lines at a readable size that never
	// overflows the 220 cm wide panel (two-digit scores like 26:24 fit).
	ScoreboardText = CreateDefaultSubobject<UTextRenderComponent>(TEXT("ScoreboardText"));
	ScoreboardText->SetupAttachment(Root);
	// Text centred vertically on the panel (panel centre Z=155) via the
	// TextCenter vertical alignment, offset -18 X in front of the -X face.
	ScoreboardText->SetRelativeLocation(TableLoc + FVector(-18.f, 0, 155.f));
	// TextRender's glyph plane faces -Y by default (the readable side points
	// -Y); Yaw +90 turns the readable face to -X, matching the panel's front
	// face, so text reads correctly (not mirrored) from the -X / court side
	// where the acceptance camera stands. Verified on-shot: Yaw -90 produced
	// mirrored glyphs from the -X viewpoint.
	ScoreboardText->SetRelativeRotation(FRotator(0.f, 90.f, 0.f));
	ScoreboardText->SetHorizontalAlignment(EHorizTextAligment::EHTA_Center);
	ScoreboardText->SetVerticalAlignment(EVerticalTextAligment::EVRTA_TextCenter);
	ScoreboardText->SetWorldSize(16.f);
	ScoreboardText->SetTextRenderColor(FColor(255, 214, 64));
	// English only: UTextRenderComponent uses the engine default font (Roboto)
	// which has no CJK glyphs; the four-line format is SET / A:B / sets / serve.
	ScoreboardText->SetText(FText::FromString(TEXT("SET 1\nA 0 : 0 B\nSETS A 0 : 0 B\nSERVE A")));
}

void AMatchOfficialManager::BuildBenches()
{
	// M11f-4: both benches sit on the SAME (-Y) sideline as the scorer table,
	// outside the free zone, split by team (A on +X, B on -X), so the whole
	// competition work area reads as one side and no bench intrudes into the
	// free zone or the stands.
	const FVector BenchALoc(420.f, -1300.f, 0.f);
	const FVector BenchBLoc(-420.f, -1300.f, 0.f);
	const FLinearColor BenchColor(0.25f, 0.40f, 0.55f);
	BenchA = MakeBlock(TEXT("BenchA"), BenchALoc + FVector(0, 0, 30.f),
		FVector(5.f, 0.4f, 0.35f), BenchColor, ECollisionEnabled::QueryOnly);
	BenchB = MakeBlock(TEXT("BenchB"), BenchBLoc + FVector(0, 0, 30.f),
		FVector(5.f, 0.4f, 0.35f), FLinearColor(0.55f, 0.30f, 0.25f), ECollisionEnabled::QueryOnly);

	// Lightweight substitutes (visual only, no collision) on both benches,
	// posed seated (short body + legs) instead of standing blocks.
	int32 SubIdx = 0;
	auto AddSub = [this, &SubIdx](const FVector& Loc, const FLinearColor& Jersey)
	{
		UStaticMeshComponent* B = MakeBlock(*FString::Printf(TEXT("Sub%d"), SubIdx), Loc + FVector(0, 0, 38.f),
			FVector(0.34f, 0.26f, 0.55f), Jersey);
		Substitutes.Add(B);
		UStaticMeshComponent* Leg = MakeBlock(*FString::Printf(TEXT("SubLeg%d"), SubIdx), Loc + FVector(0, 0, 16.f),
			FVector(0.22f, 0.24f, 0.45f), FLinearColor(0.20f, 0.21f, 0.26f));
		Substitutes.Add(Leg);
		UStaticMeshComponent* H = MakeBlock(*FString::Printf(TEXT("SubHead%d"), SubIdx), Loc + FVector(0, 0, 72.f),
			FVector(0.24f, 0.24f, 0.24f), FLinearColor(0.72f, 0.55f, 0.42f));
		Substitutes.Add(H);
		++SubIdx;
	};
	for (int32 i = -2; i <= 2; ++i)
	{
		AddSub(BenchALoc + FVector(60.f * i, -80.f, 0.f), FLinearColor(0.15f, 0.40f, 0.75f));
		AddSub(BenchBLoc + FVector(60.f * i, -80.f, 0.f), FLinearColor(0.75f, 0.25f, 0.20f));
	}
}

void AMatchOfficialManager::Whistle()
{
	if (!WhistleSound) { WhistleSound = MakeWhistleSound(this); }
	if (WhistleSound) { UGameplayStatics::PlaySound2D(this, WhistleSound); }
}

void AMatchOfficialManager::SetScorerText(const FString& Line1, const FString& Line2, const FString& Line3, const FString& Line4)
{
	if (!ScoreboardText) return;
	ScoreboardText->SetText(FText::FromString(FString::Printf(TEXT("%s\n%s\n%s\n%s"),
		*Line1, *Line2, *Line3, *Line4)));
}