// SPDX-License-Identifier: MIT
#include "Volleyball/MatchOfficialManager.h"
#include "Components/BoxComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Components/TextRenderComponent.h"
#include "Engine/StaticMesh.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Sound/SoundWaveProcedural.h"
#include "Kismet/GameplayStatics.h"
#include "SEMaterials.h"

static UMaterialInstanceDynamic* MOMakeMID(UObject* Owner, const FLinearColor& Color)
{
	return SEMaterials::MakeTint(Owner, Color);
}

/**
 * Program-generated referee whistle (single 2.2 kHz tone, ~0.35 s, soft
 * fade), streamed through a procedural USoundWave. Created at runtime so there
 * is no external audio asset, no download and no licensing question. License
 * record: generated by this project.
 */
static USoundWaveProcedural* MakeWhistleSound(UObject* Outer)
{
	const int32 SampleRate = 22050;
	const float Dur = 0.35f;
	const int32 Num = (int32)(Dur * SampleRate);
	TArray<uint8> Bytes;
	Bytes.Reserve(Num * 2);
	for (int32 i = 0; i < Num; ++i)
	{
		const float t = (float)i / (float)SampleRate;
		const float Env = FMath::Sin(PI * (float)i / (float)Num);
		const float V = FMath::Sin(2.f * PI * 2200.f * t) * 0.5f * Env;
		const int16 S = (int16)(FMath::Clamp(V, -1.f, 1.f) * 32767.f);
		Bytes.Add((uint8)(S & 0xFF));
		Bytes.Add((uint8)((S >> 8) & 0xFF));
	}
	USoundWaveProcedural* W = NewObject<USoundWaveProcedural>(Outer);
	W->SetSampleRate(SampleRate);
	W->NumChannels = 1;
	W->SampleByteSize = 2;
	W->QueueAudio(Bytes.GetData(), Bytes.Num());
	return W;
}

UStaticMeshComponent* AMatchOfficialManager::MakeBlock(const TCHAR* Name, const FVector& Loc, const FVector& Scale,
	const FLinearColor& Color, ECollisionEnabled::Type Collision)
{
	UStaticMeshComponent* C = CreateDefaultSubobject<UStaticMeshComponent>(Name);
	C->SetupAttachment(Root);
	if (UStaticMesh* Cube = LoadObject<UStaticMesh>(nullptr, TEXT("/Engine/BasicShapes/Cube.Cube")))
		C->SetStaticMesh(Cube);
	C->SetRelativeLocation(Loc);
	C->SetRelativeScale3D(Scale);
	C->SetCollisionEnabled(Collision);
	if (auto* M = MOMakeMID(C, Color)) C->SetMaterial(0, M);
	return C;
}

AMatchOfficialManager::AMatchOfficialManager()
{
	PrimaryActorTick.bCanEverTick = false;

	Root = CreateDefaultSubobject<UBoxComponent>(TEXT("Root"));
	Root->SetBoxExtent(FVector(100.f, 100.f, 10.f));
	Root->SetCollisionProfileName(TEXT("BlockAll"));
	RootComponent = Root;

	BuildStand();
	BuildScorer();
	BuildBenches();
}

void AMatchOfficialManager::BuildStand()
{
	// 1st referee stand at the +Y net end. Platform top ~245 cm so the
	// referee's eye line sits ~50 cm above the net top (243).
	const FVector StandLoc(0.f, 720.f, 0.f);

	StandPlatform = MakeBlock(TEXT("StandPlatform"), StandLoc + FVector(0, 0, 240.f),
		FVector(1.6f, 1.6f, 0.12f), FLinearColor(0.35f, 0.36f, 0.40f), ECollisionEnabled::QueryOnly);
	StandLadder = MakeBlock(TEXT("StandLadder"), StandLoc + FVector(120.f, 0, 110.f),
		FVector(0.9f, 0.9f, 2.2f), FLinearColor(0.30f, 0.31f, 0.35f));
	// Guard rails: two upright posts plus the cross bar so the platform reads
	// as a real referee tower rather than a floating slab.
	StandRailing = MakeBlock(TEXT("StandRailing"), StandLoc + FVector(0, 0, 300.f),
		FVector(1.6f, 0.10f, 0.5f), FLinearColor(0.45f, 0.47f, 0.52f));
	StandRailingPostA = MakeBlock(TEXT("StandRailingPostA"), StandLoc + FVector(-80.f, 0, 280.f),
		FVector(0.12f, 0.12f, 1.6f), FLinearColor(0.45f, 0.47f, 0.52f));
	StandRailingPostB = MakeBlock(TEXT("StandRailingPostB"), StandLoc + FVector(80.f, 0, 280.f),
		FVector(0.12f, 0.12f, 1.6f), FLinearColor(0.45f, 0.47f, 0.52f));
	StandPadding = MakeBlock(TEXT("StandPadding"), StandLoc + FVector(0, 0, 220.f),
		FVector(1.7f, 0.3f, 0.5f), FLinearColor(0.60f, 0.30f, 0.25f));

	// 1st referee (standing on the platform, facing the court = -X).
	Ref1Body = MakeBlock(TEXT("Ref1Body"), StandLoc + FVector(0, 0, 300.f),
		FVector(0.42f, 0.30f, 0.95f), FLinearColor(0.92f, 0.88f, 0.84f));
	Ref1Head = MakeBlock(TEXT("Ref1Head"), StandLoc + FVector(0, 0, 368.f),
		FVector(0.30f, 0.30f, 0.30f), FLinearColor(0.72f, 0.55f, 0.42f));

	// 2nd referee at the -Y net end, on the ground.
	Ref2Body = MakeBlock(TEXT("Ref2Body"), FVector(0.f, -720.f, 55.f),
		FVector(0.42f, 0.30f, 0.95f), FLinearColor(0.90f, 0.55f, 0.15f));
	Ref2Head = MakeBlock(TEXT("Ref2Head"), FVector(0.f, -720.f, 123.f),
		FVector(0.30f, 0.30f, 0.30f), FLinearColor(0.72f, 0.55f, 0.42f));
}

void AMatchOfficialManager::BuildScorer()
{
	// Scorer table behind the A end line, outside the free zone (X=1750).
	const FVector TableLoc(1750.f, 0.f, 0.f);
	ScorerTable = MakeBlock(TEXT("ScorerTable"), TableLoc + FVector(0, 0, 75.f),
		FVector(1.8f, 0.9f, 0.1f), FLinearColor(0.45f, 0.40f, 0.32f), ECollisionEnabled::QueryOnly);
	ScorerChair = MakeBlock(TEXT("ScorerChair"), TableLoc + FVector(80.f, 0, 30.f),
		FVector(0.5f, 0.5f, 0.6f), FLinearColor(0.35f, 0.36f, 0.40f));
	// Scorer sits behind the table, facing the court / 1st referee (-X direction).
	ScorerBody = MakeBlock(TEXT("ScorerBody"), TableLoc + FVector(70.f, 0, 105.f),
		FVector(0.40f, 0.30f, 0.90f), FLinearColor(0.25f, 0.30f, 0.45f));
	ScorerHead = MakeBlock(TEXT("ScorerHead"), TableLoc + FVector(70.f, 0, 168.f),
		FVector(0.28f, 0.28f, 0.28f), FLinearColor(0.72f, 0.55f, 0.42f));

	// Physical scorer's scoreboard device on the table: a pedestal plus a
	// tall panel whose front face (-X, toward the court and the broadcast
	// camera) carries the live text, so it reads from the stands and the
	// scorer never blocks it.
	ScoreboardDevice = MakeBlock(TEXT("ScoreboardDevice"), TableLoc + FVector(-10.f, 0, 108.f),
		FVector(1.1f, 0.6f, 0.10f), FLinearColor(0.18f, 0.19f, 0.24f), ECollisionEnabled::QueryOnly);
	ScoreboardPanel = MakeBlock(TEXT("ScoreboardPanel"), TableLoc + FVector(-10.f, 0, 150.f),
		FVector(1.05f, 0.05f, 0.85f), FLinearColor(0.08f, 0.09f, 0.14f), ECollisionEnabled::QueryOnly);

	// Live text on the panel's -X face. Yaw 180 faces the text toward the
	// court so it reads correctly from the stands / broadcast camera.
	ScoreboardText = CreateDefaultSubobject<UTextRenderComponent>(TEXT("ScoreboardText"));
	ScoreboardText->SetupAttachment(Root);
	ScoreboardText->SetRelativeLocation(TableLoc + FVector(-10.f, 0, 150.f));
	ScoreboardText->SetRelativeRotation(FRotator(0.f, 180.f, 0.f));
	ScoreboardText->SetHorizontalAlignment(EHorizTextAligment::EHTA_Center);
	ScoreboardText->SetWorldSize(22.f);
	ScoreboardText->SetTextRenderColor(FColor(255, 214, 64));
	ScoreboardText->SetText(FText::FromString(TEXT("SPIKE ELITE\nSET 1\n0 : 0")));
}

void AMatchOfficialManager::BuildBenches()
{
	// Team benches outside the free zone (Y = ±1150), along X.
	const FLinearColor BenchColor(0.25f, 0.40f, 0.55f);
	BenchA = MakeBlock(TEXT("BenchA"), FVector(200.f, 1150.f, 30.f),
		FVector(5.f, 0.4f, 0.35f), BenchColor, ECollisionEnabled::QueryOnly);
	BenchB = MakeBlock(TEXT("BenchB"), FVector(200.f, -1150.f, 30.f),
		FVector(5.f, 0.4f, 0.35f), FLinearColor(0.55f, 0.30f, 0.25f), ECollisionEnabled::QueryOnly);

	// Lightweight substitutes (visual only, no collision) on both benches,
	// posed seated (short body + legs) instead of standing blocks.
	int32 SubIdx = 0;
	auto AddSub = [this, &SubIdx](const FVector& Loc, const FLinearColor& Jersey)
	{
		UStaticMeshComponent* B = MakeBlock(*FString::Printf(TEXT("Sub%d"), SubIdx), Loc + FVector(0, 0, 38.f),
			FVector(0.34f, 0.26f, 0.55f), Jersey);
		Substitutes.Add(B);
		UStaticMeshComponent* Leg = MakeBlock(*FString::Printf(TEXT("SubLeg%d"), SubIdx), Loc + FVector(0, 0, 16.f),
			FVector(0.22f, 0.24f, 0.45f), FLinearColor(0.20f, 0.21f, 0.26f));
		Substitutes.Add(Leg);
		UStaticMeshComponent* H = MakeBlock(*FString::Printf(TEXT("SubHead%d"), SubIdx), Loc + FVector(0, 0, 72.f),
			FVector(0.24f, 0.24f, 0.24f), FLinearColor(0.72f, 0.55f, 0.42f));
		Substitutes.Add(H);
		++SubIdx;
	};
	for (int32 i = -2; i <= 2; ++i)
	{
		AddSub(FVector(200.f + i * 60.f, 1150.f - 80.f, 0.f), FLinearColor(0.15f, 0.40f, 0.75f));
		AddSub(FVector(200.f + i * 60.f, -1150.f + 80.f, 0.f), FLinearColor(0.75f, 0.25f, 0.20f));
	}
}

void AMatchOfficialManager::Whistle()
{
	if (!WhistleSound) { WhistleSound = MakeWhistleSound(this); }
	if (WhistleSound) { UGameplayStatics::PlaySound2D(this, WhistleSound); }
}

void AMatchOfficialManager::SetScorerText(const FString& Line1, const FString& Line2, const FString& Line3)
{
	if (!ScoreboardText) return;
	ScoreboardText->SetText(FText::FromString(FString::Printf(TEXT("%s\n%s\n%s"), *Line1, *Line2, *Line3)));
}